init:
    terraform init

destroy:
    terraform apply -destroy

plan:
    terraform plan

apply:
    terraform apply

pihole:
    terraform apply -target=module.pihole_vm

plex:
    terraform apply -target=module.plex_vm



    
