#cloud-config

packages:
  - curl
  - unbound
  - qemu-guest-agent

write_files:
  - path: /etc/unbound/unbound.conf.d/pi-hole.conf
    content: |
      server:
        verbosity: 1

        interface: 127.0.0.1
        port: 5335
        do-ip4: yes
        do-ip6: yes
        do-udp: yes
        do-tcp: yes

        # May be set to yes if you have IPv6 connectivity
        prefer-ip6: no

        # Use this only when you downloaded the list of primary root servers!
        root-hints: "/var/lib/unbound/root.hints"

        # Trust glue only if it is within the server's authority
        harden-glue: yes

        # Require DNSSEC data for trust-anchored zones, if such data is absent, the zone becomes bogus
        harden-dnssec-stripped: yes

        # Don't use Capitalization randomization as it known to cause DNSSEC issues sometimes
        use-caps-for-id: no

        # Reduce EDNS reassembly buffer size.
        edns-buffer-size: 1232

        # Ensure kernel buffer is large enough to not lose messages in traffic spikes
        so-rcvbuf: 1m

        # Perform prefetching of close-to-expiry message cache entries
        prefetch: yes

        # One thread should be sufficient, can be increased on beefy machines
        num-threads: 1

        # Ensure privacy of local IP ranges
        private-address: 192.168.0.0/16
        private-address: 169.254.0.0/16
        private-address: 172.16.0.0/12
        private-address: 10.0.0.0/8
        private-address: fd00::/8
        private-address: fe80::/10

  - path: /var/lib/unbound/root.hints
    content: |
      .	3600000	IN	NS	a.root-servers.net.
      a.root-servers.net.	3600000	IN	A	198.41.0.4
      .	3600000	IN	NS	b.root-servers.net.
      b.root-servers.net.	3600000	IN	A	199.9.14.201
      .	3600000	IN	NS	c.root-servers.net.
      c.root-servers.net.	3600000	IN	A	192.33.4.12
      .	3600000	IN	NS	d.root-servers.net.
      d.root-servers.net.	3600000	IN	A	199.7.91.13
      .	3600000	IN	NS	e.root-servers.net.
      e.root-servers.net.	3600000	IN	A	192.203.230.10
      .	3600000	IN	NS	f.root-servers.net.
      f.root-servers.net.	3600000	IN	A	192.5.5.241
      .	3600000	IN	NS	g.root-servers.net.
      g.root-servers.net.	3600000	IN	A	192.112.36.4
      .	3600000	IN	NS	h.root-servers.net.
      h.root-servers.net.	3600000	IN	A	198.97.190.53
      .	3600000	IN	NS	i.root-servers.net.
      i.root-servers.net.	3600000	IN	A	192.36.148.17
      .	3600000	IN	NS	j.root-servers.net.
      j.root-servers.net.	3600000	IN	A	192.58.128.30
      .	3600000	IN	NS	k.root-servers.net.
      k.root-servers.net.	3600000	IN	A	193.0.14.129
      .	3600000	IN	NS	l.root-servers.net.
      l.root-servers.net.	3600000	IN	A	199.7.83.42
      .	3600000	IN	NS	m.root-servers.net.
      m.root-servers.net.	3600000	IN	A	202.12.27.33

  - path: /etc/pihole/setupVars.conf
    content: |
      PIHOLE_INTERFACE=eth0
      PIHOLE_DNS_1=127.0.0.1#5335
      PIHOLE_DNS_2=
      QUERY_LOGGING=true
      INSTALL_WEB_SERVER=true
      INSTALL_WEB_INTERFACE=true
      LIGHTTPD_ENABLED=true
      CACHE_SIZE=10000
      DNS_FQDN_REQUIRED=true
      DNS_BOGUS_PRIV=true
      DNSMASQ_LISTENING=local
      BLOCKING_ENABLED=true
      DNSSEC=true

runcmd:
    # install pihole silently, relies on setupVars.conf file being present in /etc/pihole. it is set above
  - |
    curl -sSL https://install.pi-hole.net | bash -s -- --unattended
    
    #add some pihole configuration to save disk space and block icloud pr.  
  - |
    echo 'MAXDBDAYS=90' >> /etc/pihole/pihole-FTL.conf
    echo 'BLOCK_ICLOUD_PR=true' >> /etc/pihole/pihole-FTL.conf

  - |
    # Restart services to apply configurations
    systemctl restart unbound
    pihole restartdns

  - |
    # Set Pi-hole to start on boot
    systemctl enable pihole-FTL.service
    systemctl enable unbound

  - systemctl start qemu-guest-agent
  - systemctl enable ssh
  - reboot

final_message: "Pi-hole and Unbound installation and configuration complete!"